### ISSUE TITLE
Does not work without a domain

### ISSUE THREAD

**Issue by dazuaz** [serverless-components/fullstack-app#2]
Could not deploy /api without setting a domain

```
 Error: Failed to validate ACM certificate. Unsupported ACM certificate status FAILED
    at findOrCreateCertificate (/var/task/utils.js:421:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createOrUpdateDomain (/var/task/utils.js:886:35)
    at async Express.deploy (/var/task/serverless.js:53:7)
    at async Runtime.module.exports [as handler] (/opt/nodejs/node_modules/@serverless/core/handler.js:273:24)

8s › fullstack-api › Failed to validate ACM certificate. Unsupported ACM certificate status FAILED
```

**Comment by austencollins** [comment]
Hi @dazuaz,

Just comment out the domain in the `serverless.yml`.  I updated the main project to do this by default.
