### ISSUE TITLE
deploy --all gives "Attempting to deploy multiple instances to multiple apps" error

### ISSUE THREAD

**Issue by mileswright** [serverless-components/fullstack-app#3]
Used command  `serverless create --template-url https://github.com/serverless-components/fullstack-app`, added `.env` file with keys and domain.

Running `sls deploy --all` from the root folder gives an error 
    
    λ sls deploy --all --stage dev

    serverless ⚡ framework

    Error: Attempting to deploy multiple instances to multiple apps 
    at getTemplate (serverless\node_modules\@serverless\components\src\cli\commands\utils.js:333:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at module.exports (serverless\node_modules\@serverless\components\src\cli\commands\runAll.js:25:24)
    at Object.module.exports (serverless\node_modules\@serverless\components\src\cli\index.js:118:7)

    0s » Serverless » Attempting to deploy multiple instances to multiple apps

**Comment by mileswright** [comment]
This was due to one of the app names in one of the .yml files not being updated, they all need to be the same.
